src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date doit être au bon format")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être plus grande que la date d'aujourd'hui", groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date doit être au bon format")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doit être supérieure à la date d'arrivée")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date doit être au bon format")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Souvenir", mappedBy="booking", cascade={"persist", "remove"})
     */
    private $souvenir;

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function prePersist()
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }
        if (empty($this->amount)) {
            dump($this);
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    /**
     * @return bool
     */
    public function isBookableDates()
    {
        $notAvailableDays = $this->ad->getNotAvailableDays();
        $bookingDays = $this->getDays();

        $formatDay = function($day){
            return $day->format('Y-m-d');
        };

        $notAvailable = array_map($formatDay, $notAvailableDays);
        $days = array_map($formatDay, $bookingDays);

        foreach ($days as $day) {
            if (array_search($day, $notAvailable) !== false) {
                return false;
            }
        }
        return true;
    }

    public function getDays()
    {
        $resultat = range(
            $this->getStartDate()->getTimestamp(),
            $this->getEndDate()->getTimestamp(),
            24 * 60 * 60
        );
        $days = array_map(function ($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getSouvenir(): ?Souvenir
    {
        return $this->souvenir;
    }

    public function setSouvenir(Souvenir $souvenir): self
    {
        $this->souvenir = $souvenir;

        // set the owning side of the relation if necessary
        if ($souvenir->getBooking() !== $this) {
            $souvenir->setBooking($this);
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"email"},
 *     message="un autre utilisateur s'est déja inscrit avec cet email, merci de la modifier"
 *     )
 */
class User implements UserInterface
{
    /**
     * @Assert\EqualTo(propertyPath="hash", message="Vous n'avez pas correctement confirmé le mot de passe")
     */
    public $passwordConfirm;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner un prénom valide")
     */
    private $firstName;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner un nom valide")
     */
    private $lastName;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un mail valide")
     */
    private $email;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez renseigner une URL valide pour votre avatar")
     */
    private $picture;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255, minMessage="Votre introduction doit faire minimum 5 caractères", maxMessage="L'introduction doit faire max 255 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=5, max=255, minMessage="Votre introduction doit faire minimum 5 caractères", maxMessage="La description doit faire max 255 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Souvenir", mappedBy="partenaire")
     */
    private $souvenirs;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->souvenirs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName(): ?string
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        $roles = $this->userRoles->map(function ($role) {
            return $role->getTitle();
        })->toArray();
        $roles[] = 'ROLE_USER';
        return $roles;
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string|null The encoded password if any
     */
    public function getPassword()
    {
        return $this->hash;
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Souvenir[]
     */
    public function getSouvenirs(): Collection

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     * @param Ad $ad
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function book(Ad $ad, Request $request, EntityManagerInterface $manager)
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            $booking->setBooker($user)
                ->setAd($ad);

            if (!$booking->isBookableDates()) {
                $this->addFlash('warning', "Les dates que vous avez choisi ne peuvent etres réservées: elles sont déja prises");
            } else {
                $manager->persist($booking);
                $manager->flush();
                return $this->redirectToRoute('booking_show', ['id' => $booking->getId(), 'withAlert' => true]);
            }
        }

        return $this->render('booking/book.html.twig', [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }

    /**
     * @Route("/booking/{id}", name="booking_show")
     * @param Booking $booking
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function show(Booking $booking, Request $request, EntityManagerInterface $manager)
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
                $comment->setAd($booking->getAd())
                    ->setAuthor($this->getUser());
                $manager->persist($comment);
                $manager->flush();
                $this->addFlash('success', "Votre commentaire a bien été pris en compte");
        }
        return $this->render('booking/show.html.twig',
            ['booking' => $booking, 'form' => $form->createView()]);
    }


}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reserver l'annonce{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Réservez pour l'annonce : <em>{{ ad.title }}</em></h1>

        <p>Vous etes sur le point de réserver le bien de <strong>{{ ad.author.fullName }}</strong></p>
        {{ form_start(form) }}
        <div class="alert alert-light">
            <h2 class="h4">Donnez les dates qui vous intéressent</h2>
            <div class="row">
                <div class="col">
                    {{ form_row(form.startDate) }}
                </div>
                <div class="col">
                    {{ form_row(form.endDate) }}
                </div>
            </div>
        </div>

        <h4 class="mt-2">Montant du séjour: <span id="amount">...</span> &euro;</h4>
        <span id="days">0</span> nuit(s) à {{ ad.price | number_format(2, ',', ' ') }} &euro; par nuit
        <h4 class="mt-2">Vous avez un commentaire?</h4>
        {{ form_row(form.comment) }}
        <button type="submit" class="btn btn-success">Je réserve</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#booking_startDate, #booking_endDate').datepicker({
                format: 'dd/mm/yyyy',
                datesDisabled: [
                    {% for day in ad.notAvailableDays %}
                    "{{ day.format('d/m/Y') }}",
                    {% endfor %}
                ],
                startDate: new Date()
            });

            $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
        });

        function calculateAmount() {
            const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            if (startDate && endDate && startDate < endDate) {
                const DAY_TIME = 24 * 60 * 60 * 1000;
                const interval = endDate.getTime() - startDate.getTime();
                const days = interval / DAY_TIME;
                const amount = days * {{ ad.price }};

                $('#days').text(days);
                $('#amount').text(amount.toLocaleString('fr-FR'));
            }
        }
    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation n° {{ booking.id }}{% endblock %}

{% block body %}
    {% set ad = booking.ad %}
    {% set author = ad.author %}

    <div class="container">
        <h1 class="my-5">Votre réservation n° {{ booking.id }}</h1>

        {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
                <h4 class="alert-heading">Bravo!</h4>
                <p>
                    Votre réservation auprès de
                    <strong>
                        <a href="{{ path('user_show', {'slug': author.slug}) }}">{{ author.fullName }}</a>
                    </strong>
                    pour l'annonce
                    <strong>
                        <a href="{{ path("ads_show", {'slug': ad.slug}) }}">{{ ad.title }}</a>
                    </strong>
                    a bien été prise en compte
                </p>
            </div>
        {% endif %}

        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Détails</h2>
                    <dl class="row">
                        <dt class="col-md-4">n°</dt>
                        <dt class="col-md-8">{{ booking.id }}</dt>
                        <dt class="col-md-4">Date d'arrivée</dt>
                        <dt class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dt>
                        <dt class="col-md-4">Date de départ</dt>
                        <dt class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dt>
                        <dt class="col-md-4">Nombre de nuits</dt>
                        <dt class="col-md-8">{{ booking.duration }}</dt>
                        <dt class="col-md-4">Montant total</dt>
                        <dt class="col-md-8">{{ booking.amount | number_format(2, ',', ' ') }}</dt>
                        <dt class="col-md-4">Commentaire</dt>
                        <dt class="col-md-8">{{ booking.comment | default('Aucun commentaire') }}</dt>
                    </dl>
                    <hr>
                    <h2 class="alert-heading">Votre hôte</h2>
                    <div class="row">
                        <div class="col-md-3">
                            <img src="{{ author.picture }}" class="avatar avatar-medium"
                                 alt="Avatar de {{ author.fullName }}">
                        </div>
                        <div class="col-md-9">
                            <h4>
                                <a href="{{ path('user_show', {'slug': author.slug}) }}">{{ author.fullName }}</a>
                            </h4>
                            <span class="badge badge-primary">{{ author.ads|length }} annonce(s)</span>
                        </div>
                    </div>
                    {{ author.description | raw }}
                    <a href="{{ path('user_show', {'slug': author.slug}) }}" class="btn btn-primary">Plus d'informations
                        sur {{ author.fullName }}</a>
                </div>
            </div>
            <div class="col">
                <div class="alert alert-light">
                    <h2 class="alert-heading">Votre hébergement</h2>
                    <h4>
                        <a href="{{ path('ads_show', {'slug': ad.slug}) }}">{{ ad.title }}</a>
                    </h4>
                    <img src="{{ ad.coverImage }}" alt="Image de {{ ad.title }}" class="img-fluid">
                    {{ ad.contentAd | raw }}
                    <a href="{{ path('ads_show', {'slug': ad.slug}) }}" class="btn btn-primary">Plus d'informations</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="alert alert-light" id="comment">
                    <h2 class="alert-heading">Votre avis compte</h2>
                    {% if date() > date(booking.endDate) %}
                        {% set comment = booking.ad.commentFromAuthor(app.user) %}
                        {% if comment is not null %}
                            <blockquote>
                                {{ comment.content }}
                            </blockquote>
                            <strong>Note: </strong>{% include 'partials/rating.html.twig' with {'rating': comment.rating}%}
                        {% else %}
                            {{ form_start(form) }}
                            {{ form_widget(form) }}
                            <button type="submit" class="btn btn-success">confirmer</button>
                            {{ form_end(form) }}
                        {% endif %}
                    {% else %}
                        <p>Vous ne pourrez pas noter cette annonce tant que le voyage ne sera pas terminé</p>
                    {% endif %}
                </div>
            </div>
            <div class="col">
                <div class="alert alert-light" id="souvenir">
                    <h2 class="alert-heading">Ajouter au journal de bord</h2>
                    {% if date() > date(booking.endDate) %}
                        {% set souvenir = booking.souvenir %}
                        {% if souvenir is not null %}
                            <p>Vous avez déja enregistré vos souvenirs dans votre journal de bord</p>
                        {% else %}
                            <a href="{{ path('souvenir', {'id': booking.id}) }}" class="btn btn-primary">Ajouter votre expérience à votre journal de bord</a>
                        {% endif %}
                    {% else %}
                        <p>Vous ne pourrez pas noter cette annonce tant que le voyage ne sera pas terminé</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}