src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"title"},
 *     message="une autre annonce possède ce titre"
 *     )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255, minMessage="Le titre doit faire minimum 5 caractères", maxMessage="Le titre doit faire max 255 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=5, max=255, minMessage="L'introduction doit faire minimum 5 caractères", maxMessage="L'introduction doit faire max 255 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=5, max=255, minMessage="La description doit faire minimum 5 caractères", maxMessage="La description doit faire max 255 caractères")
     */
    private $contentAd;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer", length=255)
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContentAd(): ?string
    {
        return $this->contentAd;
    }

    public function setContentAd(string $contentAd): self
    {
        $this->contentAd = $contentAd;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return array
     */
    public function getNotAvailableDays()
    {
        $notAvailableDays = [];
        foreach ($this->bookings as $booking) {
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );
            $days = array_map(function ($dayTimestamp) {
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);
            $notAvailableDays = array_merge($notAvailableDays, $days);
        }
        return $notAvailableDays;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }
        return $this;
    }

    /**
     * @return float|int
     */
    public function getAvgRatings()
    {
        $sum = array_reduce($this->comments->toArray(), function ($total, $comment) {
            return $total + $comment->getRating();
        }, 0);

        if (count($this->comments) > 0) {
            return $sum / count($this->comments);
        }
        return 0;
    }

    /**
     * @param User $author
     * @return mixed|null
     */
    public function getCommentFromAuthor(User $author){
       foreach ($this->comments as $comment)
       {
           if($comment->getAuthor() == $author)
           {
               return $comment;
           }
       }
       return null;
    }
}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, $this->getConfiguration("Titre", "Tapez un titre d'annonce"))
            ->add('slug', TextType::class, $this->getConfiguration("Adresse web", "Tapez l'adresse web (automatique)", ['required' => false]))
            ->add('coverImage', UrlType::class, $this->getConfiguration("URL image", "Donnez une URL"))
            ->add('introduction', TextType::class, $this->getConfiguration("Introduction", "Donnez une description globale de l'annonce"))
            ->add('contentAd', TextType::class, $this->getConfiguration("Description détaillée", "Donnez une description détaillée"))
            ->add('rooms', IntegerType::class, $this->getConfiguration("Nombre de chambres", "Donnez un nombre de chambres"))
            ->add('price', MoneyType::class, $this->getConfiguration("Prix par nuit", "Indiquez le prix pour la nuit"))
            ->add('images', CollectionType::class,
                [
                    'entry_type' => ImageType::class,
                    'allow_add' => true,
                    'allow_delete' => true
                ]
            );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Data\SearchData;
use App\Entity\Ad;
use App\Form\AdType;
use App\Form\SearchType;
use App\Repository\AdRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdController extends AbstractController
{
    /**
     * @Route("/ads", name="ads_index")
     * @param AdRepository $repo
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return JsonResponse|Response
     */
    public function index(AdRepository $repo, PaginatorInterface $paginator, Request $request)
    {
        //$repo = $this->getDoctrinObjectManager e()->getRepository(Ad::class);

        $data2 = new SearchData();
        $form = $this->createForm(SearchType::class, $data2);
        $form->handleRequest($request);
        // dd($data2);

        $data = $repo->findSearch($data2);
        $ads = $paginator->paginate($data, $request->query->getInt('page', 1), 6);

        if ($request->get('ajax')) {
            return new JsonResponse([
                'content' => $this->renderView('ad/_ads.html.twig', ['ads' => $ads]),
                'sorting' => $this->renderView('ad/_sorting.html.twig', ['ads' => $ads]),
                'pagination' => $this->renderView('ad/_pagination.html.twig', ['ads' => $ads]),
            ]);
        }

        return $this->render('ad/index.html.twig', [
            'ads' => $ads,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/ads/new", name="ads_create")
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @IsGranted("ROLE_USER")
     * @return Response
     */
    public function create(Request $request, EntityManagerInterface $manager)
    {
        $ad = new Ad();
        $form = $this->createForm(AdType::class, $ad);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }
            $ad->setAuthor($this->getUser());
            $manager->persist($ad);
            $manager->flush();
            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a été enregistrée"
            );
            return $this->redirectToRoute('ads_show',
                ['slug' => $ad->getSlug()]
            );
        }

        return $this->render('ad/new.html.twig',
            ['form' => $form->createView()]
        );
    }

    /**
     * @Route("/ads/{slug}", name="ads_show")
     * @param Ad $ad
     * @return Response
     */
    public function show(Ad $ad)
    {
        //$ad = $repo->findOneBySlug($slug);
        return $this->render('ad/show.html.twig', [
            'ad' => $ad,
        ]);
    }

    /**
     * @Route("/ads/{slug}/edit", name="ads_edit")
     * @param Ad $ad
     * @param Request $request
     * @param ObjectManager $manager
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier")
     * @return Response
     */
    public function edit(Ad $ad, Request $request, EntityManagerInterface $manager)
    {
        $form = $this->createForm(AdType::class, $ad);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }
            $manager->persist($ad);
            $manager->flush();
            $this->addFlash(
                'success',
                "Les modifications de l'annonce <strong>{$ad->getTitle()}</strong> ont été enregistrées"
            );
            return $this->redirectToRoute('ads_show',
                ['slug' => $ad->getSlug()]
            );
        }
        return $this->render('ad/edit.html.twig',
            [
                'form' => $form->createView(),
                'ad' => $ad,
            ]
        );
    }


    /**
     * @Route("/ads/{slug}/delete", name="ads_delete")
     * @param Ad $ad
     * @param ObjectManager $manager
     * @return Response
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Vous n'avez pas le droit d'accéder à cette ressource")
     */
    public function delete(Ad $ad, EntityManagerInterface $manager)
    {
        $manager->remove($ad);
        $manager->flush();
        $this->addFlash(
            'success',
            "L'annonce <strong>{$ad->getTitle()}</strong> a été supprimée"
        );
        return $this->redirectToRoute("ads_index");
    }
}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug': ad.slug}) %}
<div class="col-md-4" id="ad-{{ ad.id }}" style="display: inline-block;">
    <div class="card bg-light mb-3">
        <div class="card-header text-center">
            {{ ad.rooms }} chambres, <strong>{{ ad.price | number_format(2, ',', ' ') }} &euro;/nuit</strong> <br>

            {% if ad.comments|length > 0 %}
                {% include 'partials/rating.html.twig' with {'rating':ad.avgRatings} %}
            {% else  %}
                <small>Pas encore noté</small>
            {% endif %}
        </div>
        <a href="{{ url }}">
            <img src="{{ ad.coverImage }}" alt="image de l'appartement"
                 style="height: 150px; width: 100%; display:block">
        </a>
        <div class="card-body">
            <h4 class="card-title" style="font-size: 90%;">
                <a href="{{ url }}">
                    {{ ad.title }}
                </a>
            </h4>
            <p class="card-text" style="font-size: 70%;">
                {{ ad.introduction }}
            </p>
            <a href="{{  path('ads_show', {'slug': ad.slug}) }}" class="btn btn-primary float-lg-right">En savoir
                plus</a>
            {% if app.user and app.user == ad.author %}
                <a href="{{ path('ads_edit', {'slug': ad.slug})}}" class="btn btn-secondary">Modifier l'annonce</a>
            {% endif %}
        </div>
    </div>
</div>

templates/ad/_ads.html.twig
{% for ad in ads %}
    {%- include 'ad/_ad.html.twig' -%}
{% endfor %}

templates/ad/_collection.html.twig
{% block _ad_images_widget %}
    <p>ici, vous pouvez ajouter une image</p>
    {{ form_widget(form) }}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">
            <i class="fas fa-check"></i>
            Ajouter une image
        </button>
    </div>
{% endblock %}

{% block _ad_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _ad_images_entry_widget %}
    <div class="form-group" id="block_{{ id }}">
        <div class="row">
            <div class="col-md-10">
                <div class="col">
                    {{ form_widget(form.url) }}
                    {{ form_errors(form.url) }}
                </div>
                <div class="col">
                    {{ form_widget(form.caption) }}
                    {{ form_errors(form.caption) }}
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger">X</button>
        </div>
    </div>
{% endblock %}

templates/ad/_filter.html.twig
{{ form_start(form, {attr: {class: 'filter js-filter-form'}}) }}

<div class="spinner-border js-loading" role="status" aria-hidden="true" style="display: none">
    <span class="sr-only">Loading...</span>
</div>


<div class="card bg-light mb-3">
    <div class="card-header text-center">
        Affiner ma recherche
    </div>
    <div class="card-body">
        {{ form_row(form.q) }}

        <h4>Prix</h4>
        <div class="row">
            <div class="col-md-6">
                {{ form_row(form.min) }}
            </div>
            <div class="col-md-6">
                {{ form_row(form.max) }}
            </div>
            <button onclick="return false;" class="btn btn-primary w-100 js-filter-button" style="margin-left: 10%; margin-right: 10%">Filtrer</button>
        </div>
        {{ form_end(form) }}
    </div>
</div>

templates/ad/_pagination.html.twig
{{ knp_pagination_render(ads) }}

templates/ad/_sorting.html.twig
{{ knp_pagination_sortable(ads, 'Prix', 'price') }}
{{ knp_pagination_sortable(ads, 'Chambres', 'rooms') }}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}Modification d'une annonce{% endblock %}
{% form_theme form 'ad/_collection.html.twig' %}
{% block body %}
    <div class="container">
        <h1>Modifier une nouvelle annonce {{ ad.title }}</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}lo
        <button type="submit" class="btn btn-primary">Modififer l'annonce</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('js/ad') }}
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ ad.title }}{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3">
                <div class="card card-outline-secondary my-4">
                    <div class="card-header"><h3>{{ ad.title }}
                            <a href="{{ path('booking_create', {'slug': ad.slug}) }}"
                               class="btn btn-primary">Reserver</a>
                            {% if app.user and app.user == ad.author %}
                                <a href="{{ path('ads_edit', {'slug': ad.slug}) }}" class="btn btn-secondary">Modifier
                                    l'annonce</a>
                                <a href="{{ path('ads_delete', {'slug': ad.slug}) }}"
                                   onclick="return confirm('Etes vous sur de vouloir supprimer l\'annonce : {{ ad.title }}?')"
                                   class="btn btn-danger">Supprimer l'annonce</a>
                            {% endif %}
                        </h3>
                    </div>
                    <div class="card-body">
                        <p class="h4">
                            Logement de {{ ad.rooms }} chambres pour {{ ad.price | number_format(2, ',', ' ') }} &euro;/nuit
                        </p>
                        <p>{{ ad.introduction }}</p>
                    </div>
                </div>

                <div class="card mt-4">
                    <div id="carouselExampleIndicators" class="carousel slide  my-4" data-ride="carousel">
                        <ol class="carousel-indicators">
                            {% for image in ad.images %}
                                <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}"
                                    {% if loop.first %}class="active"{% endif %}></li>
                            {% endfor %}
                        </ol>
                        <div class="carousel-inner">
                            {% for image in ad.images %}
                                <div class="carousel-item {% if loop.first %}active{% endif %}">
                                    <img class="d-block w-100" src="http://placehold.it/900x350" alt="First slide">
                                    <div class="carousel-caption d-none d-md-block">
                                        <h5>{{ ad.title }}</h5>
                                        <p>{{ image.caption }}</p>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
                           data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
                           data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ ad.contentAd | raw }}</p>
                        <a href="{{ path('booking_create', {'slug': ad.slug}) }}"
                           class="btn btn-primary">Reserver</a>
                        {% if app.user and app.user == ad.author %}
                            <a href="{{ path('ads_edit', {'slug': ad.slug}) }}" class="btn btn-secondary">Modifier
                                l'annonce</a>
                            <a href="{{ path('ads_delete', {'slug': ad.slug}) }}"
                               onclick="return confirm('Etes vous sur de vouloir supprimer l\'annonce : {{ ad.title }}?')"
                               class="btn btn-danger">Supprimer l'annonce</a>
                        {% endif %}
                    </div>
                </div>
                <hr>

                {% if ad.comments | length > 0 %}
                    <div class="card card-outline-secondary my-4">
                        <div class="card-header">
                            Note globale {% include 'partials/rating.html.twig' with {'rating':ad.avgRatings} %}
                            <small> (calculée sur {{ ad.comments|length }} avis)</small>
                        </div>
                        <div class="card-body">
                            {% for comment in ad.comments %}
                                <p>{{ comment.content }}</p>
                                <small class="text-muted">Posted by
                                    <strong>{{ comment.author.fullName }}</strong> {% include 'partials/rating.html.twig' with {'rating':comment.rating} %}
                                </small>
                                <hr>
                            {% endfor %}
                        </div>
                    </div>

                {% else %}
                    <h2>Cette annonce n'a pas encore de commentaires</h2>
                    <a href="#" class="btn btn-success">Leave a Review</a>
                {% endif %}

            </div>
            <div class="col">
                <div class="card card-outline-secondary my-4">
                    <div class="card-header">
                        {% set a = ad.author %}
                        <div class="row">
                            <div class="col-md-3">
                                <a href="{{ path('user_show', {'slug': a.slug}) }}">
                                    <img src="{{ a.picture }}" class="avatar avatar-medium"
                                         alt="Avatar de {{ a.fullName }}">
                                </a>
                            </div>
                            <div class="col">
                                <a href="{{ path('user_show', {'slug': a.slug}) }}">
                                    <h3>{{ a.fullName }}</h3>
                                </a>
                                <span class="badge badge-primary">{{ a.ads | length }} annonces</span>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        {{ a.description | raw }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/ad/show2.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ ad.title }}{% endblock %}
{% block body %}
    <div class="ad-title-class" style="background-image: url({{ ad.coverImage }})">
        <div class="container">
            <h1>{{ ad.title }}</h1>
            <p>{{ ad.introduction }}</p>
            <p class="h2">
                <strong>{{ ad.rooms }} chambres </strong> pour <strong> {{ ad.price | number_format(2, ',', ' ') }} &euro;</strong> par nuit
            </p>
            <a href="{{ path('booking_create', {'slug': ad.slug}) }}" class="btn btn-primary">Reserver</a>
            {% if app.user and app.user == ad.author %}
                <a href="{{ path('ads_edit', {'slug': ad.slug}) }}" class="btn btn-secondary">Modifier l'annonce</a>
                <a href="{{ path('ads_delete', {'slug': ad.slug}) }}"
                   onclick="return confirm('Etes vous sur de vouloir supprimer l\'annonce : {{ ad.title }}?')"
                   class="btn btn-danger">Supprimer l'annonce</a>
            {% endif %}
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3">

                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in ad.images %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}"
                                {% if loop.first %}class="active"{% endif %}></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in ad.images %}
                            <div class="carousel-item {% if loop.first %}active{% endif %}">
                                <img class="d-block w-100" src="{{ image.url }}" alt="First slide">
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>{{ ad.title }}</h5>
                                    <p>{{ image.caption }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                {{ ad.contentAd | raw }}

                <hr>

                {% if ad.comments | length > 0 %}
                    <h2 class="mb-3">Commentaires de nos voyageurs:</h2>

                    <div class="alert alert-info">
                        <h4 class="alert-heading text-center">
                            <div class="row align-items-center">
                                <div class="col">
                                    Note globale donnée par nos voyageurs
                                </div>
                                <div class="col">
                                    {% include 'partials/rating.html.twig' with {'rating':ad.avgRatings} %}
                                    <br>
                                    <small>(calculée sur {{ ad.comments|length }} avis)</small>
                                </div>
                            </div>
                        </h4>
                    </div>

                    {% for comment in ad.comments %}
                        <div class="bg-light rounded mb-3 py-3 px-3">
                            <strong>{{ comment.author.fullName }}</strong> a dit:
                            <blockquote>
                                {{ comment.content }}
                            </blockquote>
                            <strong>Note donnée {{ comment.author.fullName }}: </strong> {{ comment.rating }}
                            {% include 'partials/rating.html.twig' with {'rating':comment.rating} %}
                        </div>
                    {% endfor %}
                {% else %}
                    <h2>Cette annonce n'a pas encore de commentaires</h2>
                {% endif %}

            </div>
            <div class="col">
                {% set a = ad.author %}
                <div class="row">
                    <div class="col-md-3">
                        <a href="{{ path('user_show', {'slug': a.slug}) }}">
                            <img src="{{ a.picture }}" class="avatar avatar-medium" alt="Avatar de {{ a.fullName }}">
                        </a>
                    </div>
                    <div class="col">
                        <a href="{{ path('user_show', {'slug': a.slug}) }}">
                            <h3>{{ a.fullName }}</h3>
                        </a>
                        <span class="badge badge-primary">{{ a.ads | length }} annonces</span>
                    </div>
                </div>
                {{ a.description | raw }}
            </div>
        </div>
    </div>
{% endblock %}